package edu.escuelaing.Ejemplos;

import edu.escuelaing.Anotaciones.Test;

public class TestExample {
    
    @Test
    public static void m1()throws Exception{
        throw(new Exception("Error in m1"));
    }

    @Test
    public static void m2()throws Exception{
        throw(new Exception("Error in m2"));
    }

    @Test
    public static void m3()throws Exception{
        throw(new Exception("Error in m3"));
    }

    @Test
    public static void m4()throws Exception{
        throw(new Exception("Error in m4"));
    }

    @Test
    public static void m5()throws Exception{
        throw(new Exception("Error in m5"));
    }

    @Test
    public static void m6() throws Exception{
        throw(new Exception("Error in m6"));
    }


}
